PCB: false
batchsize: 8
color_jitter: false
data_dir: ./data/datasets/Market-1501-v15.09.15/pytorch
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids: '0'
lr: 0.05
name: ft_ResNet50
nclasses: 751
stride: 2
train_all: true
use_NAS: false
use_cpu: true
use_dense: false
warm_epoch: 0
