export PATH="${PWD}/configs:$PATH"
export PATH="${PWD}/config:$PATH"
export PATH="${PWD}/data:$PATH"
export PATH="${PWD}/engine:$PATH"
export PATH="${PWD}/layers:$PATH"
export PATH="${PWD}/modeling:$PATH"
export PATH="${PWD}/model:$PATH"
export PATH="${PWD}/solver:$PATH"
export PATH="${PWD}/tests:$PATH"
export PATH="${PWD}/tools:$PATH"
export PATH="${PWD}/utils:$PATH"

